#!/bin/bash

#Userverwaltung
#Autor: Taygun, Ismail, Enes, Alex(dremybull)
#Email: karatayta@elektronikschule.de, naumnnal@elektronikschule.de, degirmencien@elektronikschule.de, demiris@elektronikschule.de
#Version: 1.0.0

function menu(){
        clear
        echo "|----------------------------------------------|"
        echo "| Haupmenu:                                    |"
        echo "|                                              |"
        echo "|      Gruppe hinzufügen:     a                |"
        echo "|      Gruppe löschen:        d                |"
        echo "|      Nutzer hinzufügen:     h                |"
        echo "|      Nutzer löschen:        l                |"
        echo "|      Programm beenden:      X                |"
        echo "|                                              |"
        read -p "| Eingabe: " EINGABE
}

function useradd(){
        
}
function deleteuser(){
	echo "DELETEUSER"
	YESNO=0

	until [ $YESNO = 1 ]
	do
        where
        echo "Sind Sie sich sicher, dass Sie in $WHERE nach dem User suchen wollen?"
        read -p "0: nein | 1: ja" YESNO
    done
    cd /$WHERE
    ls -l $WHERE
    YESNO=0

	until [ $YESNO = 1 ]
	do
        which
        echo "Sind Sie sich sicher, dass Sie das sie den User $WHICH löschen wollen?"
        read -p "0: nein | 1: ja" YESNO
    done
    rm $WHICH
    sleep 5
}

while :
do
          menu
          case $EINGABE in
                a|A)
                        groupadd
                        ;;
                d|D)
                        groupdel
                        ;;
                h|H)
                        useradd
                        ;;
                l|L)
                        userdel
                        ;;
                  *)
                        echo "Und tschüss!"
                        exit 1
            esac
            sleep 2
done 

exit 0
done
