#!/bin/bash

#Userverwaltung
#Autor: Taygun, Ismail, Enes, Alex(dremybull)
#Email: karatayta@elektronikschule.de, naumnnal@elektronikschule.de, degirmencien@elektronikschule.de, demiris@elektronikschule.de
#Version: 1.0.0

function menu(){
        clear
        echo "|----------------------------------------------|"
        echo "| Haupmenu:                                    |"
        echo "|                                              |"
        echo "|      Gruppe hinzufügen:     a                |"
        echo "|      Gruppe löschen:        d                |"
        echo "|      Nutzer hinzufügen:     h                |"
        echo "|      Nutzer löschen:        l                |"
        echo "|      Programm beenden:      X                |"
        echo "|                                              |"
        read -p "| Eingabe: " EINGABE
}
function useradd(){
	 username=$(kdialog --inputbox "Geben Sie den zuhinzufügenden Nutzer an:")
        speicherort=$(kdialog --inputbox "An welchem Ort soll der Nutzer gespeichert werden:")
        until [ $yesno == 0 ]
	do
              yesno=$(kdialog --yesno "Sind sie sich sicher, dass Sie den Benutzer $username in $speicherort speichernwollen?")
        done
        id $username 2&> /dev/null
	if [ $? = 0 ]
	then 
		kdialog --msgbox "User $username vorhanden"
	else 
		kdialog --msgbox "User $username wird erstellt."
                cd $speicherort
                useradd $username
        fi
}
function userdel(){
	yesno-dialog where2deluser
	for I in $(find ${WHERE2DELUSER} -maxdepth 1 \( -name "*tgz" -o -name "*xz" -o -name "*bzip2" \) )
	do 
		echo "|> "$I
	done
   	yesno-dialog who2Del 
	rm ${WHO2DEL}
	if [ $? = 0 ]
	then
		echo "| ${WHO2DEL} wurde gelöscht!"
	fi
	sleep 2
}
function deletegroup(){
	echo "DELETEGROUP"
	YESNO=0

	until [ $YESNO = 1 ]
	do
        where
        echo "Sind Sie sich sicher, dass Sie in $WHERE nach der Gruppe suchen wollen?"
        read -p "0: nein | 1: ja" YESNO
    done
    cd /$WHERE
    ls -l $WHERE
    YESNO=0

	until [ $YESNO = 1 ]
	do
        which
        echo "Sind Sie sich sicher, dass Sie die Gruppe $WHICH löschen wollen?"
        read -p "0: nein | 1: ja" YESNO
    done
    rm $WHICH
    sleep 5
}

}
function groupadd(){

}

while :
do
          menu
          case $EINGABE in
                a|A)
                        groupadd
                        ;;
                d|D)
                        groupdel
                        ;;
                h|H)
                        useradd
                        ;;
                l|L)
                        userdel
                        ;;
                  *)
                        echo "Und tschüss!"
                        exit 1
            esac
            sleep 2
done 

exit 0
done

